name: Pages

on:
  push:
    branches:
      - main
    tags:

jobs:
  pages:
    runs-on: ubuntu-latest

    name: Publish GitHub Pages

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
      - name: Install Node dependencies
        run: yarn --frozen-lockfile
      - name: Build vega
        run: cd vega && yarn --frozen-lockfile && yarn build
      - name: Build the editor
        run: cd editor && yarn --frozen-lockfile && yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: editor/dist
